### ISSUE TITLE
Upgrading from 4.10.1 to 5.0.0: history/index"' has no exported member 'LocationDescriptor'.

### ISSUE THREAD

**Issue by hurrtz** [remix-run/history#846] opened 2020-11-25 16:18 UTC
Probably related to https://github.com/ReactTraining/history/issues/835

**Comment by StringEpsilon** [comment] 2020-11-25 18:41
The type definitions of history 5 are incompatible with the type definitions from @types/history. 

I've given that a secondary note in #811. Perhaps it deserves a more prominent spot.

**Comment by mjackson** [comment] 2021-08-15 23:30
This is a duplicate of #835. v5 does not require using @types/history. Instead, it comes with its own type definitions.

**Closed by mjackson** 2021-08-15 23:30 UTC
