### ISSUE TITLE
React router not working after upgrading to v 5

### ISSUE THREAD

**Issue by GaetanoPiazzolla** [remix-run/history#804] opened 2020-06-16 12:34 UTC
Hello, we've upgraded the history version to 5.0.0 without knowing it because it was set to "latest" in package.json.

What we have found is that the url in the browser gets correctly updated using "history.push()" (with both BrowserHistory and HashHistory) but the navigation is not tirggered anymore. 
Also, using react-router-dom Link component, the path gets built wrong, skipping the first "/" after the base path.

Switching back to 4.10.1 fixed the issues for us.

**Comment by duc-talentwunder** [comment] 2020-06-16 15:29
we've recognized same behaviour. url is updated after history.push but navigation is not working anymore with react-router, also no error in the console

**Comment by PulkitAgg** [comment] 2020-06-17 06:43
I am facing the same issue. It looks like there is some breaking changes in the newest version "5.0.0" of history package. For now, we can change its version to "4.10.1" which works for me.
Use bellow command for change history version 
`npm install history@4.10.1`

**Comment by zerone2** [comment] 2020-06-19 03:00
exactly same issue. createBrowserHistory doesn't work like before. 

`
const history = createBrowserHistory()
...
<Router history={history}>
  <Switch>
    <Route />
    ...
  <Switch />
<Router />
`
if I use like this, Link or history.push doesn't work

**Comment by zerone2** [comment] 2020-06-19 06:03
same issue. 
after history v5 
Link or history.push() doesn't work anymore
SO I downgrade to 4.10.1

**Comment by avindra** [comment] 2020-06-19 19:25
You probably have to update to the react router v6 alpha as well, as the v5 is explicity specifying v4 history in its dependencies. More likely than not, you will have _two_  (conflicting) history deps if you are still using react-router 5.

**Comment by avindra** [comment] 2020-06-19 19:26
This is probably a duplicate of #803

**Comment by codingwithmanny** [comment] 2020-06-20 16:52
@zerone2 you saved my sanity and my hair.
Thank you for figuring this out.

Using:
```
"history": "4.10.1",
"connected-react-router": "6.8.0",
"react-router-dom": "^5.2.0",
"react-redux": "^7.2.0",
"redux": "^4.0.5",
```

Working for me!

**Comment by progtarek** [comment] 2020-06-27 20:24
in my case I was using history version 5.0.0, I decrease to version 4.10.1, it works fine.

[ReactTraining/history #804](https://github.com/ReactTraining/history/issues/804)

**Comment by xXFracXx** [comment] 2020-07-03 14:37
PrivateRoutes seem to not work in v5.

**Comment by danutzcodrescu** [comment] 2020-07-07 08:59
same thing, we are using hash router and `history.push()` is no longer working

**Comment by ROiPinheiro** [comment] 2020-07-15 18:49
Any news about this??

**Comment by kmacute** [comment] 2020-07-24 19:22
So this is the reason why history.push() is not working, im using the version 5. okay got it, removing the history.push() maybe a bad idea on future release. i'll stick to version 4. Thanks

**Comment by phosphene47** [comment] 2020-08-07 08:10
I've just spent a few hours pulling my hair and trying to diagnose why my routes weren't matching. Thank you!

**Comment by IsaacYongTY** [comment] 2020-09-07 18:08
Yes changing to @4.10.1 solves the problem, been pulling my hair for quite some hours too!

**Comment by vodis** [comment] 2020-09-09 11:31
But if you use callback in history.block() then v4 doesn't help!

**Comment by nsisodiya** [comment] 2020-09-19 12:55
After spending sufficient  time where I am wrong, I checkout my old code which was working.
then I checked, both code is exactly same. After having good amount of headache, I compared package-lock.json file and then I found that old code is using history4 and new code is history 5. 

Yes, there is a reason why things are called "bleeding edge"...

**Comment by leticiamrosa** [comment] 2020-09-29 23:39
I was trying to figure out why the history it wasn't passed for my components, after the comments here I did the downgrade to history@4.10.1 and everything is work now.

Thanks, guys 👏

**Comment by McPatto** [comment] 2020-11-16 19:45
Hi! Is there any other solution besides downgrading to v-4?

**Comment by kmacute** [comment] 2020-11-17 00:34
> Hi! Is there any other solution besides downgrading to v-4?

Thats' the solution xD

**Comment by pankajsanam** [comment] 2020-12-03 11:22
> Hi! Is there any other solution besides downgrading to v-4?

You can also upgrade react-router to 6 (alpha) because react-router 5.2 is using dependencies from history 4 and that is causing conflict issues. But personally, I would suggest to downgrade the history lib itself until react-router 6 is in a stable state.

**Comment by alex-shamshurin** [comment] 2020-12-20 19:29
May be router should check if history 5 version and do throw

**Comment by ea167** [comment] 2021-01-07 19:05
Same problem here, history v5 is incompatible with the current latest react-router.

**Comment by Denis-Step** [comment] 2021-01-14 00:18
Wasted an entire day on this. So frustrating. Will update as soon as I test different versions. How was this problem traced to the history package?

**Comment by olof-nord** [comment] 2021-01-26 09:30
I also came across this issue. Was solved by downgrading `history` to the last 4.x version.

```
    "history": "^4.10.1",
    "react-router-dom": "^5.2.0",
```

**Comment by sztahanova** [comment] 2021-02-23 19:52
Jesus, guys, I just lost 2 days on desperately trying to figure out what went wrong in my project. Without any errors in the console or otherwise, the routing just stopped working, it drove me crazy... Lucky that I have just a few deps in my package.json so it didnt take ages to drill down to the faulty one... Hope it will be fixed soon!

**Comment by balovbohdan** [comment] 2021-06-16 13:23
I also have issues with history 5. Decided to downgrade to ^4.

**Comment by Archivec** [comment] 2021-08-15 20:40
Upgrading history to v5.0.1 and react-router-dom to v6.0.0-beta.1 solved the issue for us.
Tried with withRouters, props.history.push and none of them rerenders component though pushes the correct url.

**Comment by mjackson** [comment] 2021-08-15 23:14
React Router 5 has [a dependency on history v4](https://github.com/remix-run/react-router/blob/51925ded7530516cfb8d9756fa0190e3b4f49387/packages/react-router/package.json#L40), not v5. You should use history v4 with React Router 4/5.

> we've upgraded the history version to 5.0.0 without knowing it because it was set to "latest" in package.json

You shouldn't ever use `latest` as the version dependency in your package.json because when new major versions are released with breaking changes your app will break. You can read more about how to set dependencies correctly in [the package.json documentation on `dependencies` field](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies) where you will find links to references on how to use semver correctly as well.

For a React Router v5 project, if you want to install `history` separately you should have this in your package.json:

```
"dependencies": {
  "history": "^4.9.0"
}
```

**Closed by mjackson** 2021-08-15 23:14 UTC

**Comment by ipsips** [comment] 2021-08-28 07:10
history is installed separately and used alongside react-router when there's a need to create history before instantiating BrowserRouter. For that purpose I propose react-router expose it's own createHistory methods (which could simply wrap the history.js api) so we wouldn't have to manually keep an eye on the versions - it's tedious and wastes our time

**Comment by Ashutosh-Bhadauriya** [comment] 2021-10-06 10:49
> I also came across this issue. Was solved by downgrading `history` to the last 4.x version.
> 
> ```
>     "history": "^4.10.1",
>     "react-router-dom": "^5.2.0",
> ```

but link is still not working for me

**Comment by Manik92** [comment] 2021-11-20 10:23
> Hi! Is there any other solution besides downgrading to v-4?

Yes Instead of useHistory we can use "useNavigate" for the upgraded version

Eg:

import {useNavigate} from  "react-router-dom";
const navigate = useNavigate();

In method:

navigate("/<path>", {replace: true})

Reference:
https://reactnavigation.org/docs/navigation-prop

**Comment by alirezaaali** [comment] 2022-02-21 22:16
The useNavigate is not working in class component

**Comment by sztahanova** [comment] 2022-02-22 06:35
> The useNavigate is not working in class component

Hooks don't work in class components, they are meant to be used in functional components.

**Comment by jiangdan53** [comment] 2022-06-05 14:15
I used the connected react router in my development, but when I update the routing data with Redux, I am prompted with the pathname error. How can I solve it

> I am facing the same issue. It looks like there is some breaking changes in the newest version "5.0.0" of history package. For now, we can change its version to "4.10.1" which works for me. Use bellow command for change history version `npm install history@4.10.1`

**Comment by LeminGhori** [comment] 2024-06-24 15:38
in localhost app is runing good 
but when i create build show this error 
history.ts:494 Uncaught 
Error
    at l (history.ts:494:11)
    at x (components.tsx:421:3)
    at Ei (react-dom.production.min.js:167:137)
    at Es (react-dom.production.min.js:290:337)
    at wu (react-dom.production.min.js:280:389)
    at yu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at au (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)

**Comment by sdancer75** [comment] 2025-05-09 09:55
> redux



> [@zerone2](https://github.com/zerone2) you saved my sanity and my hair. Thank you for figuring this out.
> 
> Using:
> 
> ```
> "history": "4.10.1",
> "connected-react-router": "6.8.0",
> "react-router-dom": "^5.2.0",
> "react-redux": "^7.2.0",
> "redux": "^4.0.5",
> ```
> 
> Working for me!

It didn't work in my setup :-(
